version: '3.9'
services:
  redis:
    container_name: redisdb
    image: 'redislabs/redismod'
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    entrypoint: redis-server
      --loadmodule /usr/lib/redis/modules/redisearch.so
      --loadmodule /usr/lib/redis/modules/rejson.so
      --loadmodule /usr/lib/redis/modules/redisbloom.so
      --loadmodule /usr/lib/redis/modules/redisgears.so
      --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
